// render_testing/angular-dom-render-testing/src/app/app.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {MenuComponent} from "./menu/menu.component";
import {RowComponent} from "./row/row.component";
import {CommonModule} from "@angular/common";

@Component({
	selector: 'app-root',
	standalone: true,
	imports : [MenuComponent,RowComponent,CommonModule],
	templateUrl: './app.component.html',
	styleUrl: './app.component.css',
	changeDetection: ChangeDetectionStrategy.OnPush

})
export class AppComponent {
	data:{id:number,label:string}[] = [];
	numberOfRows:number = 0;

	buildRows(amount:number, currentLength:number) {
		console.log("build")
		let returnArray = [];
		for (let i = 0; i < amount; i++) {
			returnArray.push({id: i + currentLength, label: 'label ' + (i + currentLength)});
		}
		return returnArray;
	}

	createRows(amount:number){
		this.numberOfRows = amount;
		this.data = this.buildRows(amount, 0);
	}

	addRows(amount:number){
		this.numberOfRows +=amount;
		let newRows = this.buildRows(amount,this.numberOfRows)
		this.data = this.data.concat(newRows)
	}

	removeRows(){
		this.data = [];
		this.numberOfRows = 0;
	}

	trackByFn(index: any,item:{id:number,label:string}) {
		return item.id;
	}
}

// render_testing/vue-dom-render-testing/src/App.vue
<template>
    <div class="app">
        <Menu v-bind="{createRows, addRows, removeRows}"/>
        <table class="table">
            <tbody>
                <Row
                    v-for="item in data"
                    :id="item.id"
                    :label="item.label"
                    :key="item.id"
                />
            </tbody>
      </table>
    </div>
</template>

<script>
import Menu from './components/Menu.vue'
import Row from './components/Row.vue'

export default {
    name: 'App',
    components: {
        Menu,
        Row,
    },
    data() {
        return {
            numberOfRows: 0,
            data: [],
        };
    },
    methods: {
        createRows(amount){
            this.numberOfRows = amount;
            this.data =this.buildRows(amount,0);
        },
        addRows(amount){
            this.numberOfRows += amount;
            let tmp_data = this.data;
            this.data = tmp_data.concat(this.buildRows(amount,this.data.length));
        },
        removeRows(){
            this.numberOfRows = 0;
            this.data = [];
        },
        buildRows(amount,currentLength){
            let returnArray= [];
            for(let i = 0; i<amount; i++){
                returnArray.push({id: i+currentLength, label:'label '+(i+currentLength)});
            }
            return returnArray;
        }
    }
}
</script>

<style>

</style>
