// render_testing/react-dom-render-testing/src/components/Row.js
import {Component} from 'react';

export default class Row extends Component{
    id = this.props.id;
    label = this.props.label;

    render() {
        return (
            <tr>
                <td> {this.id} </td>
                <td className="col-md-4"> {this.label} </td>
            </tr>
        );
    }
}

// vue-dom-render-testing/src/components/Row.vue
<script>
export default {
    name: 'Row',
    props: {
        id:Number,
        label: String,
    },
    methods: {

  },
}
</script>

<template>
    <tr>
        <td class="small-col" > {{$props.id}} </td>
        <td class="big-col"> {{$props.label}} </td>
    </tr>
</template>

<style scoped>

</style>
