// render_testing/vue-dom-render-testing/src/components/Menu.vue
<script>
export default {
    name: 'HelloWorld',
    props: {
        createRows:Function,
        addRows: Function,
        removeRows: Function,
        numberOfRows: Number,
    },
}
</script>

<template>
    <div class="menu">
        <div class="framework">
            <h1>Framework: Vue3</h1>
        </div>
        <div class="row-count">
            <p>total number of rows: {{numberOfRows}}</p>
        </div>
        <div class="button-container">
            <button class="btn" v-on:click="createRows(1000)">
                create 1000
            </button>
            <button class="btn" v-on:click="addRows(1000)">
                add 1000
            </button>
            <button class="btn" v-on:click="createRows(10000)">
                create 10000
            </button>
            <button class="btn" v-on:click="createRows(10000)">
                add 10000
            </button>
            <button class="btn" v-on:click="removeRows()">
                remove all
            </button>
        </div>
    </div>
</template>

<style scoped>
</style>

// render_testing/react-dom-render-testing/src/components/Menu.js
import {Component} from "react";

export default class Menu extends Component {
    create = this.props.create;
    add = this.props.add;
    remove = this.props.remove;
    count = this.props.count;

    render() {
        return (
        <div className="menu">
            <div className="framework">
                <h1>Framework: React</h1>
            </div>
            <div className="row-count">
                <p>total number of rows: {this.count}</p>
            </div>
            <div className="button-container">
                <button className="btn" onClick={()=>this.create(1000)}>
                    create 1000
                </button>
                <button className="btn" onClick={()=>this.add(1000)}>
                    add 1000
                </button>
                <button className="btn" onClick={()=>this.create(10000)}>
                    create 10000
                </button>
                <button className="btn" onClick={()=>this.add(10000)}>
                    add 10000
                </button>
                <button className="btn" onClick={()=>this.remove()}>
                    remove all
                </button>
            </div>
        </div>
        );
    }
}
